apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
 name: hippo
spec:
 image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis-ha:centos8-13.4-3.1-0
 postgresVersion: 13
 postGISVersion: "3.1"
 users:
 - name: tileserv
   databases:
   - "postgres"
 - name: postgres
 instances:
   - name: instance1
     replicas: 2
     dataVolumeClaimSpec:
       accessModes:
       - "ReadWriteOnce"
       resources:
         requests:
           storage: 1Gi
 backups:
   pgbackrest:
     image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.33-2
     repoHost:
       dedicated: {}
     repos:
     - name: repo1
       volume:
         volumeClaimSpec:
           accessModes:
           - "ReadWriteOnce"
           resources:
             requests:
               storage: 1Gi
